package com.markit.pe.portfoliodata;

public enum Currency {

	AED,ARS,AUD,BRL,CAD,CHF,CLF,CLP,CNY,COP,CZK,DEM,DKK,DOP,FRF,
	GBP,GHS,HKD,HRK,HUF,IDR,ILS,INR,ITL,JPY,KES,KRW,LKR,MAD,MXN,MYR,NGN,NOK,
	NZD,PEN,PHP,PLN,RON,RSD,RUB,
	SEK,SGD,SKK,THB,TRL,TRY,TWD,UGX,USD,UYU,VEF,ZAR,EUR
	
}
