logging:
  level:
    org.springframework.web: INFO
    org.springframework.data: DEBUG

endpoints:
  restart:
    enabled: true
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#    date-format: yyyy-MM-dd
#    date-format: dd-MMM-yyyy
#    time-zone: UTC
