server:
  port: 8085
  context-path: /compdata-service

message: "HELLO This is ComparableData-Service QA"


spring:
  datasource:
    url: jdbc:sqlserver://lon6dvedmsql01:1433;databaseName=PE_INT;integratedSecurity=true;
    username: 
    password: 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dbcp:
      test-while-idle: true
      validation-query: Select 1
    
   
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none      
    show-sql: true



      